INSERT INTO BOOKS (ID, TITLE,AUTHOR_ID,GENRE_ID) VALUES (1, 'book1',1,1);

INSERT INTO AUTHOR (ID,AUTHORNAME) VALUES (1,'author1');

INSERT INTO GENRE (ID,GENRETITLE) VALUES (1,'genre1');

INSERT INTO COMMENT (ID,BOOKID,COMMENTTEXT) VALUES (1,2,'COMMENT FOR BOOK!');

